routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!

Route::get("/", function () {
    return view("welcome");
});
|
*/



//Testes para fins didáticos
/*
Route::get("/requisicoes", "SeriesController@testarRequests");

//Aulas
Route::get("/", "SeriesController@index")->name("listar_series");
Route::get("/series", "SeriesController@index")->name("listar_series");

Route::get("/series/criar", "SeriesController@create")
    ->name("form_criar_serie")
    ->middleware('auth');
    
Route::post("/series/criar", "SeriesController@store")->middleware('auth');
Route::post("/series/editar/{id}", "SeriesController@editarSerie")->middleware('auth');
Route::delete("/series/remover/{serie_id}", "SeriesController@destroyWithoutDeleteOnCascade")
    ->name("remover_serie")
    ->middleware('auth');

Route::get("/series/{serie_id}/temporadas", "TemporadasController@index")
    ->name("listar_temporadas");

Route::get("/temporadas/{temporada}/episodios", "EpisodiosController@index")
    ->name("listar_episodios");

Route::post("/temporadas/{temporada}/episodios/assistir", "EpisodiosController@assistir")
    ->name("form_episodios_assistidos")
    ->middleware('auth');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/entrar', 'EntrarController@index')->name('home');
Route::post('/entrar', 'EntrarController@entrar')->name('entrar');
Route::get('/registrar', 'RegistrarController@create')->name('form_registrar');
Route::post('/registrar', 'RegistrarController@store')->name('registrar');

Route::get('/sair', function () {

    Auth::logout();
    return redirect('entrar');
})->name('sair');Auth::routes();
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get("/", "HomeController@index")->name('home')->middleware('auth');


Route::group(['middleware' => 'auth'], function () {
	
	Route::get('assembleia','AssembleiaController@index')->name('assembleia');

	//Administrador
	Route::group(['middleware' => 'admin:1'], function () {
		
		Route::get('typography', function () {
			return view('pages.typography');
		})->name('typography');

		Route::get('icons', function () {
			return view('pages.icons');
		})->name('icons');

		Route::get('map', function () {
			return view('pages.map');
		})->name('map');

		Route::get('notifications', function () {
			return view('pages.notifications');
		})->name('notifications');

		Route::get('rtl-support', function () {
			return view('pages.language');
		})->name('language');
		/**------------------ */


		
		Route::get('table-list', function () {
			return view('pages.table_list');
		})->name('table');

		Route::get('blank', function () {
			return view('pages.blank');
		})->name('blank');

		Route::get('form', function () {
			return view('pages.form');
		})->name('form');

				
		Route::group(['prefix' => 'tipoPessoa'], function () {
			Route::get('','TipoPessoaController@index')->name('tipo_pessoa');
			Route::get('criar','TipoPessoaController@create')->name('create_tipo_pessoa');
			Route::post('salvar','TipoPessoaController@store')->name('save_tipo_pessoa');

			Route::get('editar/{id}','TipoPessoaController@edit')->name('edit_tipo_pessoa');
			Route::put('salvar', "TipoPessoaController@update")->name('save_tipo_pessoa');
			Route::delete("{id}", "TipoPessoaController@destroy")->name('delete_tipo_pessoa');
		});

		Route::group(['prefix' => 'tipoMorador'], function () {
			Route::get('','TipoMoradorController@index')->name('tipo_morador');
			Route::get('criar','TipoMoradorController@create')->name('create_tipo_morador');
			Route::post('salvar','TipoMoradorController@store')->name('save_tipo_morador');
	
			Route::get('editar/{id}','TipoMoradorController@edit')->name('edit_tipo_morador');
			Route::put('salvar', "TipoMoradorController@update")->name('save_tipo_morador');
			Route::delete("{id}", "TipoMoradorController@destroy")->name('delete_tipo_morador');
		});

		Route::group(['prefix' => 'situacao_assembleia'], function () {
			Route::get('','SituacaoAssembleiaController@index')->name('situacao_assembleia');
			Route::get('criar','SituacaoAssembleiaController@create')->name('create_situacao_assembleia');
			Route::post('salvar','SituacaoAssembleiaController@store')->name('save_situacao_assembleia');
			Route::get('editar/{id}','SituacaoAssembleiaController@edit')->name('edit_situacao_assembleia');
			Route::put('salvar', "SituacaoAssembleiaController@update")->name('save_situacao_assembleia');
			Route::delete("{id}", "SituacaoAssembleiaController@destroy")->name('delete_situacao_assembleia');
		});
		

		Route::group(['prefix' => 'torre'], function () {
			Route::get('','TorreController@index')->name('torre');
			Route::get('criar','TorreController@create')->name('create_torre');
			Route::post('salvar','TorreController@store')->name('save_torre');
			Route::get('editar/{id}','TorreController@edit')->name('edit_torre');
			Route::put('salvar', "TorreController@update")->name('save_torre');
			Route::delete("{id}", "TorreController@destroy")->name('delete_torre');
		});

		Route::group(['prefix' => 'unidade'], function () {
			Route::get('','UnidadeController@index')->name('unidade');
			Route::get('criar','UnidadeController@create')->name('create_unidade');
			Route::post('salvar','UnidadeController@store')->name('save_unidade');
	
			Route::get('editar/{id}','UnidadeController@edit')->name('edit_unidade');
			Route::put('salvar', "UnidadeController@update")->name('save_unidade');
			Route::delete("{id}", "UnidadeController@destroy")->name('delete_unidade');
		});

		Route::group(['prefix' => 'condomino'], function () {
			Route::get('','CondominoController@index')->name('condomino');
			Route::get('criar','CondominoController@create')->name('create_condomino');
			Route::post('salvar','CondominoController@store')->name('save_condomino');
	
			Route::get('editar/{id}','CondominoController@edit')->name('edit_condomino');
			Route::put('salvar', "CondominoController@update")->name('save_condomino');
			Route::delete("{id}", "CondominoController@destroy")->name('delete_condomino');
		});

		Route::group(['prefix' => 'assembleia'], function () {
			
			Route::get('criar','AssembleiaController@create')->name('create_assembleia');
			Route::post('salvar','AssembleiaController@store')->name('save_assembleia');
	
			Route::get('editar/{id}','AssembleiaController@edit')->name('edit_assembleia');
			Route::put('salvar', "AssembleiaController@update")->name('save_assembleia');

			Route::get("{id}", "AssembleiaController@show");
			Route::delete("{id}", "AssembleiaController@destroy");
		});

		Route::group(['prefix' => 'usuario'], function () {
			Route::get('','UserController@index')->name('usuario');
			Route::get('criar','UserController@create')->name('create_usuario');
			Route::post('salvar','UserController@store')->name('save_usuario');
	
			Route::get('editar/{id}','UserController@edit')->name('edit_usuario');
			Route::put('salvar', "UserController@update")->name('save_usuario');
			Route::delete("{id}", "UserController@destroy")->name('delete_usuario');
		});

		Route::group(['prefix' => 'arquivos'], function () {
			
			Route::delete('deleteJson/{id}', 'ArquivoController@deleteJson')->name('delete_json_arquivo');
		});

	});

});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Auth::routes();

app/User.php
<?php

namespace App;

use App\Condomino;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'admin','condomino_id', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    //Relacionamento OneToOne - Um usuario pertence a um condomino 
    public function condomino(){
        
        return $this->belongsTo(Condomino::class);
    }

     /**
     * Get the categoria full name.
     *
     * @return string
     */
    public function getAdminStrAttribute() {

        if($this->admin=="1"){

            return "Administrador";
        }
        return "Usuário Comum";
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Condomino;
use App\Daos\UserDao;
use App\Configs\UserConfig;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\UserFormRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * 
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $users = User::query()
            ->orderBy("name")->get();

        $tableThLabels = UserConfig::tableThLabels();

        $mensagem = $request->session()->get("mensagem");
		$tipoAlert = $request->session()->get("tipoAlert");
        
        return view('pages.users.index', compact("users", "tableThLabels", "mensagem", "tipoAlert"));
        
    }

    public function edit($id, UserDao $userDao){

		$usuario = $userDao->findById($id, false, false);
	
		if($usuario!=null){	

			$data =  $this->fillData($usuario);	
		
			return view("pages.users.form", compact("data"));
		}

		$request->session()
                ->flash(
                    "mensagem",
                    "Usuário não encontrado"
                );
            
		$request->session()
			->flash(
				"tipoAlert",
				"alert-danger"
			);
		return redirect()->route("usuario");
    }

    public function update(UserFormRequest $request, UserDao $userDao, UserController $userController){
    
		$dados = $request->input();
		$usuario = $userDao->update($dados);
			
		if($usuario){

			$nome = $usuario->nome;

					$request->session()
				->flash(
					"mensagem",
					"{$nome} foi atualizado(a) com sucesso."
				);
			//	$request->session()->put(...)

			$request->session()
				->flash(
					"tipoAlert",
					"alert-success"
				);

			return redirect()->route("usuario");
		}
    }

    public function destroy (Request $request, UserDao $userDao){
    
        $resposta = $userDao->delete($request->id);
     
		if($resposta["msg"]==""){

            $nome = $resposta["nome"];

			$request->session()
                ->flash(
                    "mensagem",
                    "{$nome} removido(a) com sucesso"
                );
            
			$request->session()
				->flash(
					"tipoAlert",
					"alert-success"
				);
		}else{

			$request->session()
                ->flash(
                    "mensagem",
                    $resposta["msg"]
                );

			$request->session()
				->flash(
					"tipoAlert",
					"alert-danger"
				);
		}

        return redirect()->route("usuario");
	}

    public function saveCondominoInUser(Condomino $condomino){
        
        $randomPass = Str::random(8);
        $hashedRandomPassword = Hash::make($randomPass);

        return User::create([
            "name" => trim(mb_strtoupper($condomino->nome)),
            "email" => $condomino->email,
            "admin"=> "0",
            "condomino_id"=> $condomino->id,
            "password" => Hash::make($hashedRandomPassword),
        ]);
    }

    private function fillData($usuario){

		$data = (object)array();

		if($usuario!=null){
					
			$data = $usuario;
			$data->titlePage = "Editar Usuário";
			$data->activePage = "usuario/editar/{$usuario->id}";
			$data->cardTitle = "Editar";
		}

		return $data;

	}
}

resources/views/pages/users/form.blade.php
@extends('layouts.app', ['activePage' => $data->activePage, 'titlePage' => __($data->titlePage)])

@section('content')

<div class="content">
    <div class="container-fluid">
        <div class="container-fluid">

            @include('components.messages_feedback')
          
            <div class="col-md-12">

                <div class="card ">
                    <div class="card-header card-header-rose card-header-text">
                        <div class="card-text">
                            <h4 class="card-title">{{ $data->cardTitle}}</h4>
                        </div>
                    </div>
                    <div class="card-body ">
                        <form method="post" action="{{ route('save_usuario') }}" class="form-horizontal"
                            enctype='multipart/form-data'>
                            @if(isset($data->id) && $data->id!=0)
                                <input type="hidden" id="txtId" name="txtId" value="{{ $data->id }}">
                                @method('PUT')
                            @endif

                            @csrf
                            
                            <div class="row">
                                <label class="col-sm-2 col-form-label obrigatorio">Nome</label>
                                <div class="col-sm-10">
                                    <div class="form-group bmd-form-group">
                                        <input type="text" class="form-control" id="txtNome" name="txtNome" readonly
                                            value="{{ old('txtNome') ? old('txtNome') : $data->name}}">
                                        <span class="bmd-help">Nome do Usuário - Somente Leitura.</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 col-form-label obrigatorio">Email</label>
                                <div class="col-sm-10">
                                    <div class="form-group bmd-form-group">
                                        <input type="email" class="form-control " id="txtEmail" name="email" readonly
                                        maxlength="200" value="{{ old('txtEmail') ? old('txtEmail') : $data->email}}">
                                        <span class="bmd-help">Email - Somente Leitura.</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <label class="col-sm-2 col-form-label label-checkbox">Administrador</label>
                                <div class="col-sm-10 checkbox-radios">

                                    @php
                                    $checked = old('optAdmin') ? old('optAdmin') :
                                    $data->admin;
                                    @endphp
                                    <div class="form-check form-check-inline">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="optAdmin"
                                                {{ $checked == '1' ? 'checked' : '' }} 
                                                value="1"> Sim
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="optAdmin"
                                                {{ $checked != '1' ? 'checked' : '' }} 
                                                value="0"> Não
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            
                            @php /*
                            <div class="row">
                                <label class="col-sm-2 col-form-label">Gerar senha aleatória</label>
                                <div class="col-sm-10">
                                    <div class="form-group bmd-form-group">
                                        <a role="button" onclick="userController.generateRandomStr(document.querySelector('#txtRandomPass'))"
                                        class="btn btn-info">{{ __('Gerar') }}</a>

                                        <input type="text" class="form-control " id="txtRandomPass" name="txtRandomPass" 
                                        maxlength="8" value="{{ old('txtRandomPass') }}" readonly>
                                       
                                    </div>
                                </div>
                            </div>
                            */
                            @endphp
                            <div class="card ">

                                <div class="card-footer ml-auto mr-auto">
                                    <button type="submit" class="btn btn-primary">{{ __('Salvar') }}</button>
                                    <a role="button" href="{{ route('usuario') }}" class="btn btn-light">{{ __('Voltar') }}</a>

                                </div>
                               
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')

<script type="text/javascript" src="{!! asset('js/controllers/UserController.js') !!}"></script>
<script type="text/javascript">
    let userController = new UserController();
</script>
@endsection

resources/views/pages/users/index.blade.php
@extends('layouts.app', ['activePage' => 'usuarios', 'titlePage' => __('Usuários')])

<?php use App\Configs\UserConfig; ?>

<link rel="stylesheet" type="text/css" href="{!! asset('js/terceiros/DataTables/css/jquery.dataTables.min.css') !!}">


@section('content')
<div class="content">
    <div class="container-fluid">


        @if (Auth::user() && Auth::user()->admin)
        <div class="col-sm-10">
            <div class="form-group bmd-form-group">
                <a href="{{ route('create_condomino') }}" role="button" class="btn btn-info">
                    <span class="material-icons">add</span>
                    <span>{{ UserConfig::titleNew() }}</span>
                </a>

            </div>
        </div>

        @include('components.messages_feedback')
        @endif

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">{{ UserConfig::titleCardPageIndex() }}</h4>
                        <p class="card-category">{{ UserConfig::categoryCardPageIndex() }}</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="usuarios" class="table display">
                                <thead class=" text-primary">
                                    @foreach ($tableThLabels as $label)
                                    <th>
                                        {{ $label }}
                                    </th>

                                    @endforeach
                                    <th class="td-actions text-right">
                                        Ações
                                    </th>

                                </thead>
                                <tbody>

                                    @foreach ($users as $user)

                                    <tr>
                                        <td><a href="{{ route('edit_usuario', $user->id) }}"> {{ $user->id}} </a>
                                        </td>

                                        <td class="text-primary"><a
                                                href="{{ route('edit_usuario', $user->id) }}">{{ $user->name}} </a>
                                        </td>

                                        <td class="text-primary"><a
                                                href="{{ route('edit_usuario', $user->id) }}">{{ $user->email}} </a>
                                        </td>

                                        <td class="text-primary"><a
                                                href="{{ route('edit_usuario', $user->id) }}">{{ $user->admin_str}} </a>
                                        </td>


                                        <td class="text-right">
                                            <span>

                                                <span>
                                                    <a role="button"
                                                        href="{{ route('edit_usuario', $user->id) }}"
                                                        title="Editar" class="btn btn-primary btn-link btn-sm">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                </span>


                                                @if (Auth::user() && Auth::user()->admin)
                                                <span>
                                                    <form method="post"
                                                        action="{{ route('delete_usuario', ['id' => $user->id]) }}"
                                                        onsubmit="return confirm('Tem certeza que deseja remover {{ addslashes( $user->nome )}}?')">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" title="Remover"
                                                            class="btn btn-danger btn-link btn-sm">
                                                            <i class="material-icons">close</i>
                                                        </button>
                                                    </form>
                                                </span>
                                                @endif

                                            </span>
                                        </td>
                                    </tr>

                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection

@section('scripts')
<script type="text/javascript" src="{!! asset('js/terceiros/DataTables/js/jquery-3.5.1.js') !!}"></script>
<script type="text/javascript" src="{!! asset('js/terceiros/DataTables/js/jquery.dataTables.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('js/components/DataTableCompontent.js') !!}"></script>
<script type="text/javascript">
let dataTableComponent = new DataTableCompontent('#usuarios');
dataTableComponent.init();
</script>
@endsection